version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: optoutwebservice
    container_name: optoutweb
    restart: unless-stopped
    volumes:
      - .:/var/www/html
  
  optoutwebservicewebserver:
    build:
      context: .
      dockerfile: ./docker/Docker_Nginx
    image: nginx
    container_name: optoutwebserver
    restart: unless-stopped
    ports:
      - "95:80"
    volumes: 
      - .:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
        - web
        - optoutwebservicedb
  
  optoutwebservicedb:
    image: mysql:5.7.22
    container_name: optoutwebservicedb
    environment:
      MYSQL_DATABASE: timeline
      MYSQL_ROOT_PASSWORD: 7akHjm2Hzj_RNL3KA
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local