<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNkkpgBc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNkkpgBc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNkkpgBc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNkkpgBc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNkkpgBc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NkkpgBc',
    'container.build_id' => 'adce2d3b',
    'container.build_time' => 1684828624,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNkkpgBc');
