<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4hlAU9T\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4hlAU9T/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4hlAU9T.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4hlAU9T\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4hlAU9T\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4hlAU9T',
    'container.build_id' => '6f5c325c',
    'container.build_time' => 1684835862,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4hlAU9T');
